spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api
---
spring:
  profiles: localtest
  datasource:
    platform: h2
    schema: classpath:/scripts/sql/schema-h2.sql
    data: classpath:/scripts/sql/data-h2.sql
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type: trace
server:
  address: localhost
  port: 8080
---
spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/storefront-db
    username: storefront
    password: $70r3fr0n7
    platform: POSTGRESQL
    schemaName: TRAINING_STOREFRONT